name: Docker Image CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      #        with:
      #          repo-token: ${{ secrets.REGISTRY_TOKEN }}
      - name: Build the Docker image
        run: >
          vn=$(cat version);
          echo ${{ secrets.REGISTRY_TOKEN }} | docker login ghcr.io -u ${{ secrets.REGISTRY_USER }} --password-stdin;
          docker build -t ghcr.io/jaceklangertuda/mts11.lf7.umfrage.app:$vn -f Dockerfile .;
          docker push ghcr.io/jaceklangertuda/mts11.lf7.umfrage.app:$vn;
